In [1]:
import math
from sympy.matrices import Matrix
import sympy
import numpy as np
from sympy.abc import x,y
from sympy import *
init_printing( use_latex='mathjax' )
f = Function("f")
h = symbols("h")
x0=symbols("x0")

In [2]:
right=[92228496, 106021537, 123202624, 132164569, 151325798, 179323175, 203211926, 226545805, 248709873, 281421906]

In [3]:
N = symbols("N")
N = 3

In [4]:
x = [1910+i*10 for i in range(10)]
print (x)

[1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]


Для пункта в) будет

In [5]:
matrix = []

In [6]:
for i in range(10):
    matrix.append([0]*N)

In [7]:
for i in range(0, 10):
    for j in range(0, N):
        matrix[i][j] = (x[i]-1955)**j

In [8]:
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        print(matrix[i][j], end = ' ')
    print()

1 -45 2025 
1 -35 1225 
1 -25 625 
1 -15 225 
1 -5 25 
1 5 25 
1 15 225 
1 25 625 
1 35 1225 
1 45 2025 


In [9]:
t_matrix = np.transpose(matrix)

In [10]:
for i in range(len(t_matrix)):
    for j in range(len(t_matrix[i])):
        print(t_matrix[i][j], end = ' ')
    print()

1 1 1 1 1 1 1 1 1 1 
-45 -35 -25 -15 -5 5 15 25 35 45 
2025 1225 625 225 25 25 225 625 1225 2025 


In [11]:
total = t_matrix.dot(matrix)
print(total)

[[      10        0     8250]
 [       0     8250        0]
 [    8250        0 12086250]]


In [12]:
total_r = t_matrix.dot(right)
print(total_r)

[ 1744155709   117202791 -1141873883]


In [13]:
np.linalg.solve(total, total_r)

array([ 3.99426561e+08,  1.42063989e+04, -2.72740594e+05])

Теперь все тоже самое для г)

In [19]:
matrix1 = []

In [20]:
for i in range(10):
    matrix1.append([0]*N)

In [21]:
for i in range(0, 10):
    for j in range(0, N):
        matrix1[i][j] = ((x[i]-1955)/45)**j

In [22]:
for i in range(len(matrix1)):
    for j in range(len(matrix1[i])):
        print(matrix1[i][j], end = ' ')
    print()

1.0 -1.0 1.0 
1.0 -0.7777777777777778 0.6049382716049383 
1.0 -0.5555555555555556 0.308641975308642 
1.0 -0.3333333333333333 0.1111111111111111 
1.0 -0.1111111111111111 0.012345679012345678 
1.0 0.1111111111111111 0.012345679012345678 
1.0 0.3333333333333333 0.1111111111111111 
1.0 0.5555555555555556 0.308641975308642 
1.0 0.7777777777777778 0.6049382716049383 
1.0 1.0 1.0 


In [23]:
t_matrix1 = np.transpose(matrix1)

In [24]:
for i in range(len(t_matrix1)):
    for j in range(len(t_matrix1[i])):
        print(t_matrix1[i][j], end = ' ')
    print()

1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 
-1.0 -0.7777777777777778 -0.5555555555555556 -0.3333333333333333 -0.1111111111111111 0.1111111111111111 0.3333333333333333 0.5555555555555556 0.7777777777777778 1.0 
1.0 0.6049382716049383 0.308641975308642 0.1111111111111111 0.012345679012345678 0.012345679012345678 0.1111111111111111 0.308641975308642 0.6049382716049383 1.0 


In [25]:
total1 = t_matrix1.dot(matrix1)
print(total1)

[[ 1.00000000e+01 -1.11022302e-16  4.07407407e+00]
 [-1.11022302e-16  4.07407407e+00  1.11022302e-16]
 [ 4.07407407e+00  1.11022302e-16  2.94741655e+00]]


In [26]:
total_r1 = t_matrix1.dot(right)
print(total_r1)

[1.74415571e+09 3.84379377e+08 7.37534195e+08]


In [27]:
np.linalg.solve(total1, total_r1)

array([1.65887714e+08, 9.43476653e+07, 2.09320128e+07])

Используя построенные приближения для предсказания численности населения США в 2010 году и сравним с точным результатом в
$\textbf{308745538}$ человек

В случае в) получили

In [18]:
(3.99426561e+08) + (2010-1955)*(1.42063989e+04) +((2010-1955)**2)*(-2.72740594e+04)

317703883.2545

В случае г) получили

In [29]:
(1.65887714e+08) + ((2010-1955)/45)*(9.43476653e+07) +(((2010-1955)/45)**2)*(2.09320128e+07)

312470336.3888889

Используя многочлены аппроксимация данных в смысле МНК дает хорошую точность