In [1]:
import math
from sympy.matrices import Matrix
import sympy
import numpy as np
from sympy.abc import x,y
from sympy import *
init_printing( use_latex='mathjax' )
f = Function("f")
h = symbols("h")
x0=symbols("x0")

In [2]:
right=[92228496, 106021537, 123202624, 132164569, 151325798, 179323175, 203211926, 226545805, 248709873, 281421906]

In [110]:
N = symbols("N")
N = 5

In [67]:
x = [1910+i*10 for i in range(10)]
print (x)

[1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]


Для пункта в) будет

In [68]:
matrix = []

In [69]:
for i in range(10):
    matrix.append([0]*N)

In [70]:
for i in range(0, 10):
    for j in range(0, N):
        matrix[i][j] = (x[i]-1955)**j

In [71]:
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        print(matrix[i][j], end = ' ')
    print()

1 -45 
1 -35 
1 -25 
1 -15 
1 -5 
1 5 
1 15 
1 25 
1 35 
1 45 


In [72]:
t_matrix = np.transpose(matrix)

In [73]:
for i in range(len(t_matrix)):
    for j in range(len(t_matrix[i])):
        print(t_matrix[i][j], end = ' ')
    print()

1 1 1 1 1 1 1 1 1 1 
-45 -35 -25 -15 -5 5 15 25 35 45 


In [74]:
total = t_matrix.dot(matrix)
print(total)

[[  10    0]
 [   0 8250]]


In [75]:
total_r = t_matrix.dot(right)
print(total_r)

[1744155709  117202791]


In [76]:
np.linalg.solve(total, total_r)

array([1.74415571e+08, 1.42063989e+04])

Подставляя сюда все значения $N = 2, 3, 4, 5$, получим соответствующего вида полиномы:

$$N = 2: 1.74415571 \cdot 10^8 + 1.42063989\cdot 10^4 \cdot (x-1955)$$

$$N = 3: 3.99426561 \cdot 10^8 + 1.42063989\cdot 10^4 \cdot (x-1955) - 2.72740594 \cdot 10^4 \cdot (x-1955)^2$$

$$N = 4: 3.99426561 \cdot 10^8 + 5.47529166\cdot 10^2 \cdot (x-1955) - 2.72740594 \cdot 10^4 \cdot (x-1955)^2 + 9.32346058 (x-1955)^3$$

$$N = 5: 4.17292362 \cdot 10^5 + 5.47529166\cdot 10^2 \cdot (x-1955) + 7.43134478 \cdot 10^3 \cdot (x-1955)^2 + 9.32346058 (x-1955)^3 + 1.38891235 \cdot 10^2 \cdot (x-1955)^4$$

Ошибки предсказания будут тогда:

$N = 2$

In [77]:
(1.74415571e+08) + (2010-1955)*(1.42063989e+04)

175196922.9395

$N = 3$

In [78]:
(3.99426561e+08) + (2010-1955)*(1.42063989e+04) +((2010-1955)**2)*(-2.72740594e+04)

317703883.2545

$N = 4$

In [79]:
(3.99426561e+08) + (2010-1955)*(5.47529166e+02) +((2010-1955)**2)*(-2.72740594e+04) + 9.32346058*((2010-1955)**3)

318503836.17312753

$N = 5$

In [80]:
(4.17292362e+05) + (2010-1955)*(5.47529166e+02) +((2010-1955)**2)*(7.43134478e+04) + (9.32346058e+00)*((2010-1955)**3) + (1.38891235e+01)*((2010-1955)**4)

353890937.54231495

Теперь все тоже самое для г)

In [111]:
matrix1 = []

In [112]:
for i in range(10):
    matrix1.append([0]*N)

In [113]:
for i in range(0, 10):
    for j in range(0, N):
        matrix1[i][j] = ((x[i]-1955)/45)**j

In [114]:
for i in range(len(matrix1)):
    for j in range(len(matrix1[i])):
        print(matrix1[i][j], end = ' ')
    print()

1.0 -1.0 1.0 -1.0 1.0 
1.0 -0.7777777777777778 0.6049382716049383 -0.4705075445816187 0.3659503124523701 
1.0 -0.5555555555555556 0.308641975308642 -0.1714677640603567 0.09525986892242037 
1.0 -0.3333333333333333 0.1111111111111111 -0.03703703703703703 0.012345679012345677 
1.0 -0.1111111111111111 0.012345679012345678 -0.001371742112482853 0.00015241579027587256 
1.0 0.1111111111111111 0.012345679012345678 0.001371742112482853 0.00015241579027587256 
1.0 0.3333333333333333 0.1111111111111111 0.03703703703703703 0.012345679012345677 
1.0 0.5555555555555556 0.308641975308642 0.1714677640603567 0.09525986892242037 
1.0 0.7777777777777778 0.6049382716049383 0.4705075445816187 0.3659503124523701 
1.0 1.0 1.0 1.0 1.0 


In [115]:
t_matrix1 = np.transpose(matrix1)

In [116]:
for i in range(len(t_matrix1)):
    for j in range(len(t_matrix1[i])):
        print(t_matrix1[i][j], end = ' ')
    print()

1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 
-1.0 -0.7777777777777778 -0.5555555555555556 -0.3333333333333333 -0.1111111111111111 0.1111111111111111 0.3333333333333333 0.5555555555555556 0.7777777777777778 1.0 
1.0 0.6049382716049383 0.308641975308642 0.1111111111111111 0.012345679012345678 0.012345679012345678 0.1111111111111111 0.308641975308642 0.6049382716049383 1.0 
-1.0 -0.4705075445816187 -0.1714677640603567 -0.03703703703703703 -0.001371742112482853 0.001371742112482853 0.03703703703703703 0.1714677640603567 0.4705075445816187 1.0 
1.0 0.3659503124523701 0.09525986892242037 0.012345679012345677 0.00015241579027587256 0.00015241579027587256 0.012345679012345677 0.09525986892242037 0.3659503124523701 1.0 


In [117]:
total1 = t_matrix1.dot(matrix1)
print(total1)

[[ 1.00000000e+01  3.33066907e-16  4.07407407e+00 -2.22044605e-16
   2.94741655e+00]
 [ 3.33066907e-16  4.07407407e+00  0.00000000e+00  2.94741655e+00
   0.00000000e+00]
 [ 4.07407407e+00  0.00000000e+00  2.94741655e+00  0.00000000e+00
   2.50430433e+00]
 [-2.22044605e-16  2.94741655e+00  0.00000000e+00  2.50430433e+00
   0.00000000e+00]
 [ 2.94741655e+00  0.00000000e+00  2.50430433e+00  0.00000000e+00
   2.28629303e+00]]


In [118]:
total_r1 = t_matrix1.dot(right)
print(total_r1)

[1.74415571e+09 3.84379377e+08 7.37534195e+08 2.76719162e+08
 5.40972309e+08]


In [119]:
np.linalg.solve(total1, total_r1)

array([ 1.65421570e+08,  9.69980016e+07,  2.49415057e+07, -3.66343405e+06,
       -3.96059666e+06])

Подставляя сюда все значения $N = 2, 3, 4, 5$, получим соответствующего вида полиномы:

$$N = 2: 1.74415571 \cdot 10^8 + 9.43476653 \cdot 10^7 \cdot \frac{x-1955}{45}$$

$$N = 3: 1.65887714 \cdot 10^8 + 9.43476653 \cdot 10^7 \cdot \frac{x-1955}{45} + 2.09320128 \cdot 10^7 \cdot (\frac{x-1955}{45})^2$$

$$N = 4: 1.65887714 \cdot 10^8 + 9.69980016 \cdot 10^7 \cdot \frac{x-1955}{45} + 2.09320128 \cdot 10^7 \cdot (\frac{x-1955}{45})^2 - 3.66343405 \cdot 10^6 \cdot (\frac{x-1955}{45})^3$$

$$N = 5: 1.65421570 \cdot 10^8 + 9.69980016 \cdot 10^7 \cdot \frac{x-1955}{45} + 2.49415057 \cdot 10^7 \cdot (\frac{x-1955}{45})^2 - 3.66343405 \cdot 10^6 \cdot (\frac{x-1955}{45})^3 - 3.96059666 \cdot 10^6 \cdot (\frac{x-1955}{45})^4$$

Ошибки предсказания будут тогда:

$N = 2$

In [120]:
(1.74415571e+08) + ((2010-1955)/45)*(9.43476653e+07)

289729384.14444447

$N = 3$

In [121]:
(1.65887714e+08) + ((2010-1955)/45)*(9.43476653e+07) + (2.09320128e+07)*(((2010-1955)/45)**2)

312470336.3888889

$N = 4$

In [122]:
(1.65887714e+08) + ((2010-1955)/45)*(9.69980016e+07) + (2.09320128e+07)*(((2010-1955)/45)**2) + (-3.66343405e+06)*(((2010-1955)/45)**3)

309020979.6299725

$N = 5$

In [123]:
(1.65421570e+08) + ((2010-1955)/45)*(9.69980016e+07) + (2.49415057e+07)*(((2010-1955)/45)**2) + (-3.66343405e+06)*(((2010-1955)/45)**3) + (-3.96059666e+06)*(((2010-1955)/45)**4)

305706176.0070248

Используя построенные приближения для предсказания численности населения США в 2010 году и сравнив с точным результатом в
$\textbf{308745538}$ человек убеждаемся, что используя многочлены аппроксимация данных в смысле МНК дает хорошую точность